version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can
  # use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool,
  # so you don't have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: circleci/python:3.9.5

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_ci.txt
      - run:
          name: check code
          command: |
            . venv/bin/activate
            python -m compileall pykerio
            python -m pycodestyle pykerio
            python -m flake8 pykerio
            python -m build --outdir=dist .
            python -m pip install --verbose dist/*.whl
            python -m pip list
            python -m pip freeze
            ls -laR .
            python -m pip uninstall --yes --verbose pykerio
      - run:
          name: tests
          command: |
            . venv/bin/activate
            python -m pytest --verbose --capture=no tests/enums
            # Disabled interfaces as actually the demo server is not reachable anymore
            # python -m pytest --verbose --capture=no tests/interfaces
            python -m pytest --verbose --capture=no tests/lists
            python -m pytest --verbose --capture=no tests/structs
            python -m pytest --verbose --capture=no tests/types
